// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIeWGhbpdgu1ykrc9R8U0TjNQYC1HdqG8',
    appId: '1:1056609215323:ios:10a99e6125c2351ef6707e',
    messagingSenderId: '1056609215323',
    projectId: 'organicfarming3-f95bc',
    storageBucket: 'organicfarming3-f95bc.firebasestorage.app',
    iosBundleId: 'com.example.goviArana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHkxG67ENhfHJhUVER3ldIi9XOjU2-nc0',
    appId: '1:1056609215323:web:d5ada65de0418398f6707e',
    messagingSenderId: '1056609215323',
    projectId: 'organicfarming3-f95bc',
    authDomain: 'organicfarming3-f95bc.firebaseapp.com',
    storageBucket: 'organicfarming3-f95bc.firebasestorage.app',
    measurementId: 'G-DFW62SJLF8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkxG67ENhfHJhUVER3ldIi9XOjU2-nc0',
    appId: '1:1056609215323:web:020bf04971021c19f6707e',
    messagingSenderId: '1056609215323',
    projectId: 'organicfarming3-f95bc',
    authDomain: 'organicfarming3-f95bc.firebaseapp.com',
    storageBucket: 'organicfarming3-f95bc.firebasestorage.app',
    measurementId: 'G-M57PF2ZPBV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIeWGhbpdgu1ykrc9R8U0TjNQYC1HdqG8',
    appId: '1:1056609215323:ios:10a99e6125c2351ef6707e',
    messagingSenderId: '1056609215323',
    projectId: 'organicfarming3-f95bc',
    storageBucket: 'organicfarming3-f95bc.firebasestorage.app',
    iosBundleId: 'com.example.goviArana',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWM-jQZe7k3fLn-TAqhqcGF1U4ku9AS4',
    appId: '1:1056609215323:android:f8409869025eebc8f6707e',
    messagingSenderId: '1056609215323',
    projectId: 'organicfarming3-f95bc',
    storageBucket: 'organicfarming3-f95bc.firebasestorage.app',
  );

}